### ISSUE TITLE
Question: Integration with Flume (for Zipkin and Graphite)

### ISSUE THREAD

**Issue by pronzato** [kristofa/brave#56]
Hi Kristof,

I've got a graphite server and flume running with your example flume.conf from flume-zipkin-metrics-sink model (which I looking to use to keep directing regular spans to the Zipkin backend but direct spans with durations to the Graphite server).

Have a couple of quick questions before I try it out:

1. Do I need to put both of your dist jars on the flume classpath (i.e. flume-zipkin-collector-sink & flume-zipkin-metrics-sink, or do I just need the flume-zipkin-metrics-sink)?

2. With regards to changes required at my application which uses your brave impl:

Do I still keep using the ZipkinSpanCollector but just re-configure it to point to the flume scribe source 1463 instead?

i.e. the only change from the application point of view to simply change the port configured for the ZipkinSpanCollector from 9410 to 1463?

Regards

Gianni

**Comment by pronzato** [comment]
Tried changing my client application from using com.github.kristofa.brave.zipkin.ZipkinSpanCollector with 9410 to com.github.kristofa.brave.zipkin.ZipkinSpanCollector with 1463 but got the following exceptions in my client code (attached both client and flume logs at end of this comment).  

Would you be able to help clarify what changes are needed at the client to use flume correctly?

Regards

Gianni

===============================
CLIENT LOG (WHEN SENDING SPAN)
===============================

2015-01-04 11:36:35,081 ERROR [SpanProcessingThread] Exception when trying to log Span.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Software caused connection abort: recv failed
       at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
       at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
       at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
       at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
       at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
       at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)
       at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297)
       at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204)
       at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
       at com.twitter.zipkin.gen.scribe$Client.recv_Log(scribe.java:83)
       at com.twitter.zipkin.gen.scribe$Client.Log(scribe.java:70)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.log(SpanProcessingThread.java:119)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.log(SpanProcessingThread.java:109)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.call(SpanProcessingThread.java:95)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.call(SpanProcessingThread.java:35)
       at java.util.concurrent.FutureTask.run(FutureTask.java:262)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
       at java.net.SocketInputStream.socketRead0(Native Method)
       at java.net.SocketInputStream.read(SocketInputStream.java:152)
       at java.net.SocketInputStream.read(SocketInputStream.java:122)
       at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
       at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
       ... 18 more
2015-01-04 11:36:35,083 ERROR [ZipkinCollectorClientProvider] Thrift exception.
org.apache.thrift.transport.TTransportException: java.net.SocketException: Software caused connection abort: recv failed
       at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
       at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
       at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
       at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
       at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
       at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)
       at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297)
       at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204)
       at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
       at com.twitter.zipkin.gen.scribe$Client.recv_Log(scribe.java:83)
       at com.twitter.zipkin.gen.scribe$Client.Log(scribe.java:70)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.log(SpanProcessingThread.java:119)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.log(SpanProcessingThread.java:109)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.call(SpanProcessingThread.java:95)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.call(SpanProcessingThread.java:35)
       at java.util.concurrent.FutureTask.run(FutureTask.java:262)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
       at java.net.SocketInputStream.socketRead0(Native Method)
       at java.net.SocketInputStream.read(SocketInputStream.java:152)
       at java.net.SocketInputStream.read(SocketInputStream.java:122)
       at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
       at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
       ... 18 more
2015-01-04 11:36:35,085 INFO  [SpanProcessingThread] Got new client with new connection. Logging with new client.
2015-01-04 11:36:35,086 ERROR [SpanProcessingThread] Logging spans with new client also failed. 2 spans are lost!
org.apache.thrift.transport.TTransportException: java.net.SocketException: Connection reset
       at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:129)
       at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
       at org.apache.thrift.transport.TFramedTransport.readFrame(TFramedTransport.java:129)
       at org.apache.thrift.transport.TFramedTransport.read(TFramedTransport.java:101)
       at org.apache.thrift.transport.TTransport.readAll(TTransport.java:84)
       at org.apache.thrift.protocol.TBinaryProtocol.readAll(TBinaryProtocol.java:378)
       at org.apache.thrift.protocol.TBinaryProtocol.readI32(TBinaryProtocol.java:297)
       at org.apache.thrift.protocol.TBinaryProtocol.readMessageBegin(TBinaryProtocol.java:204)
       at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:69)
       at com.twitter.zipkin.gen.scribe$Client.recv_Log(scribe.java:83)
       at com.twitter.zipkin.gen.scribe$Client.Log(scribe.java:70)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.log(SpanProcessingThread.java:127)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.log(SpanProcessingThread.java:109)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.call(SpanProcessingThread.java:95)
       at com.github.kristofa.brave.zipkin.SpanProcessingThread.call(SpanProcessingThread.java:35)
       at java.util.concurrent.FutureTask.run(FutureTask.java:262)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
       at java.net.SocketInputStream.read(SocketInputStream.java:196)
       at java.net.SocketInputStream.read(SocketInputStream.java:122)
       at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
       at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
       ... 18 more


===========
FLUME LOGS
===========

04 Jan 2015 11:30:58,163 INFO  [lifecycleSupervisor-1-0] (org.apache.flume.node.PollingPropertiesFileConfigurationProvider.start:61)  - Configuratio
n provider starting
04 Jan 2015 11:30:58,171 INFO  [conf-file-poller-0] (org.apache.flume.node.PollingPropertiesFileConfigurationProvider$FileWatcherRunnable.run:133) 
- Reloading configuration file:conf/flume.conf
04 Jan 2015 11:30:58,182 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:zip
kin-sink1
04 Jan 2015 11:30:58,182 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:gra
phite-sink1
04 Jan 2015 11:30:58,182 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:gra
phite-sink1
04 Jan 2015 11:30:58,183 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:930)  - Added sinks: zi
pkin-sink1 graphite-sink1 Agent: agent1
04 Jan 2015 11:30:58,183 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:zip
kin-sink1
04 Jan 2015 11:30:58,183 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:gra
phite-sink1
04 Jan 2015 11:30:58,183 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:zip
kin-sink1
04 Jan 2015 11:30:58,184 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:gra
phite-sink1
04 Jan 2015 11:30:58,185 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:gra
phite-sink1
04 Jan 2015 11:30:58,185 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:zip
kin-sink1
04 Jan 2015 11:30:58,185 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration$AgentConfiguration.addProperty:1016)  - Processing:zip
kin-sink1
04 Jan 2015 11:30:58,219 INFO  [conf-file-poller-0] (org.apache.flume.conf.FlumeConfiguration.validateConfiguration:140)  - Post-validation flume co
nfiguration contains configuration for agents: [agent1]
04 Jan 2015 11:30:58,219 INFO  [conf-file-poller-0] (org.apache.flume.node.AbstractConfigurationProvider.loadChannels:150)  - Creating channels
04 Jan 2015 11:30:58,244 INFO  [conf-file-poller-0] (org.apache.flume.channel.DefaultChannelFactory.create:40)  - Creating instance of channel ch2 t
ype memory
04 Jan 2015 11:30:58,254 INFO  [conf-file-poller-0] (org.apache.flume.node.AbstractConfigurationProvider.loadChannels:205)  - Created channel ch2
04 Jan 2015 11:30:58,254 INFO  [conf-file-poller-0] (org.apache.flume.channel.DefaultChannelFactory.create:40)  - Creating instance of channel ch1 t
ype memory
04 Jan 2015 11:30:58,255 INFO  [conf-file-poller-0] (org.apache.flume.node.AbstractConfigurationProvider.loadChannels:205)  - Created channel ch1
04 Jan 2015 11:30:58,256 INFO  [conf-file-poller-0] (org.apache.flume.source.DefaultSourceFactory.create:39)  - Creating instance of source scribe-s
ource1, type org.apache.flume.source.scribe.ScribeSource
04 Jan 2015 11:30:58,289 INFO  [conf-file-poller-0] (org.apache.flume.sink.DefaultSinkFactory.create:40)  - Creating instance of sink: zipkin-sink1,
type: com.github.kristofa.flume.ZipkinSpanCollectorSink
04 Jan 2015 11:30:58,337 INFO  [conf-file-poller-0] (com.github.kristofa.flume.ZipkinSpanCollectorSink.configure:165)  - Configuring ZipkinSpanColle
ctorSink. hostname: 127.0.0.1, port: 9410, batchsize: 25, timeout: 2000
04 Jan 2015 11:30:58,341 INFO  [conf-file-poller-0] (org.apache.flume.sink.DefaultSinkFactory.create:40)  - Creating instance of sink: graphite-sink
1, type: com.github.kristofa.flume.ZipkinMetricsSink
04 Jan 2015 11:30:58,372 INFO  [conf-file-poller-0] (com.github.kristofa.flume.MetricReporterBuilder.configure:67)  - Graphite host: 127.0.0.1
04 Jan 2015 11:30:58,372 INFO  [conf-file-poller-0] (com.github.kristofa.flume.MetricReporterBuilder.configure:68)  - Graphite port: 2003
04 Jan 2015 11:30:58,373 INFO  [conf-file-poller-0] (com.github.kristofa.flume.MetricReporterBuilder.configure:72)  - Reporter poll time in minutes:
1
04 Jan 2015 11:30:58,373 INFO  [conf-file-poller-0] (com.github.kristofa.flume.MetricReporterBuilder.configure:77)  - Reservoir: uniform
04 Jan 2015 11:30:58,380 INFO  [conf-file-poller-0] (com.github.kristofa.flume.ZipkinMetricsSink.configure:133)  - batchsize: 25
04 Jan 2015 11:30:58,390 INFO  [conf-file-poller-0] (org.apache.flume.node.AbstractConfigurationProvider.getConfiguration:119)  - Channel ch2 connec
ted to [scribe-source1, graphite-sink1]
04 Jan 2015 11:30:58,390 INFO  [conf-file-poller-0] (org.apache.flume.node.AbstractConfigurationProvider.getConfiguration:119)  - Channel ch1 connec
ted to [scribe-source1, zipkin-sink1]
04 Jan 2015 11:30:58,432 INFO  [conf-file-poller-0] (org.apache.flume.node.Application.startAllComponents:138)  - Starting new configuration:{ sourc
eRunners:{scribe-source1=EventDrivenSourceRunner: { source:org.apache.flume.source.scribe.ScribeSource{name:scribe-source1,state:IDLE} }} sinkRunner
s:{zipkin-sink1=SinkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@184dd658 counterGroup:{ name:null counters:{} } }, graphite-sink1=Si
nkRunner: { policy:org.apache.flume.sink.DefaultSinkProcessor@1e3337df counterGroup:{ name:null counters:{} } }} channels:{ch2=org.apache.flume.chan
nel.MemoryChannel{name: ch2}, ch1=org.apache.flume.channel.MemoryChannel{name: ch1}} }
04 Jan 2015 11:30:58,439 INFO  [conf-file-poller-0] (org.apache.flume.node.Application.startAllComponents:145)  - Starting Channel ch2
04 Jan 2015 11:30:58,451 INFO  [conf-file-poller-0] (org.apache.flume.node.Application.startAllComponents:145)  - Starting Channel ch1
04 Jan 2015 11:30:58,724 INFO  [lifecycleSupervisor-1-1] (org.apache.flume.instrumentation.MonitoredCounterGroup.register:119)  - Monitored counter
group for type: CHANNEL, name: ch1: Successfully registered new MBean.
04 Jan 2015 11:30:58,725 INFO  [lifecycleSupervisor-1-1] (org.apache.flume.instrumentation.MonitoredCounterGroup.start:95)  - Component type: CHANNE
L, name: ch1 started
04 Jan 2015 11:30:58,731 INFO  [lifecycleSupervisor-1-0] (org.apache.flume.instrumentation.MonitoredCounterGroup.register:119)  - Monitored counter
group for type: CHANNEL, name: ch2: Successfully registered new MBean.
04 Jan 2015 11:30:58,732 INFO  [lifecycleSupervisor-1-0] (org.apache.flume.instrumentation.MonitoredCounterGroup.start:95)  - Component type: CHANNE
L, name: ch2 started
04 Jan 2015 11:30:58,732 INFO  [conf-file-poller-0] (org.apache.flume.node.Application.startAllComponents:173)  - Starting Sink zipkin-sink1
04 Jan 2015 11:30:58,734 INFO  [lifecycleSupervisor-1-1] (org.apache.flume.instrumentation.MonitoredCounterGroup.register:119)  - Monitored counter
group for type: SINK, name: zipkin-sink1: Successfully registered new MBean.
04 Jan 2015 11:30:58,734 INFO  [lifecycleSupervisor-1-1] (org.apache.flume.instrumentation.MonitoredCounterGroup.start:95)  - Component type: SINK,
name: zipkin-sink1 started
04 Jan 2015 11:30:58,741 INFO  [conf-file-poller-0] (org.apache.flume.node.Application.startAllComponents:173)  - Starting Sink graphite-sink1
04 Jan 2015 11:30:58,743 INFO  [lifecycleSupervisor-1-5] (org.apache.flume.instrumentation.MonitoredCounterGroup.register:119)  - Monitored counter
group for type: SINK, name: graphite-sink1: Successfully registered new MBean.
04 Jan 2015 11:30:58,744 INFO  [lifecycleSupervisor-1-5] (org.apache.flume.instrumentation.MonitoredCounterGroup.start:95)  - Component type: SINK,
name: graphite-sink1 started
04 Jan 2015 11:30:58,750 INFO  [conf-file-poller-0] (org.apache.flume.node.Application.startAllComponents:184)  - Starting Source scribe-source1
04 Jan 2015 11:30:58,859 INFO  [Thread-1] (org.apache.flume.source.scribe.ScribeSource$Startup.run:99)  - Starting Scribe Source on port 1463
04 Jan 2015 11:31:01,811 INFO  [lifecycleSupervisor-1-7] (org.apache.flume.instrumentation.MonitoredCounterGroup.register:119)  - Monitored counter
group for type: SOURCE, name: scribe-source1: Successfully registered new MBean.
04 Jan 2015 11:31:01,812 INFO  [lifecycleSupervisor-1-7] (org.apache.flume.instrumentation.MonitoredCounterGroup.start:95)  - Component type: SOURCE
, name: scribe-source1 started
04 Jan 2015 11:31:33,740 ERROR [Thread-4] (org.apache.thrift.server.TNonblockingServer$FrameBuffer.read:468)  - Read an invalid frame size of -72089
9. Are you using TFramedTransport on the client side?

**Comment by pronzato** [comment]
Upgraded to your latest codebase 2.4.1 and everything seems to work now.  Spans are now reaching Zipkin and Metrics.  Very, very, cool ..
